[package]
name = "MiniawyManager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs = "0.0.5"
libc = "0.2.141"
procfs = "0.15.1"
sysinfo = "0.28.4"
users = "0.11.0"
